### ISSUE TITLE
code_gs Ban Appeal

### ISSUE THREAD

**Issue by Kefta** [MFSiNC/SkidCheck-2.0#12]
```["STEAM_0:0:32955110"] = "code_gs, VAC banned, suspected cheater (pHack)",```

The VAC ban on my account is from MW2 four years ago. I did not earn the ban, and instead, was from the previous owner of this account who gave it to me since I did not own GMod or CS:S at the time. As for pHack, I did not and still do not have any involvement with the venture, but rather, I am only a developer for the server community.

**Comment by MFSiNC** [comment]
Removed. Will sync tomorrow morning.

**Comment by Kefta** [comment]
Thank you!
