### ISSUE TITLE
Ryuzaki - You've banned my new, fresh account.

### ISSUE THREAD

**Issue by banksymate** [MFSiNC/SkidCheck-2.0#32]
STEAM_0:1:28861.
I hadn't played gmod in ages before I added you. I added you a while ago to see if you could help me with HAC and you declined me, blocked me, and added my new account to the skidcheck for god knows how you found out my old account was linked to the new. There is nothing in my gmod folder related to cheating and I can screenshot and attach all folders if you'd like. Though it probably doesn't matter cause you always say "Once a cheater, always a cheater" or something of that sort.

**Comment by MFSiNC** [comment]
You're banned for:

"Dismay (stealing files), VAC banned, Ban evasion (5 alts, List_A), Member of 7 hack/troll groups, 12 year old skiddie, BAN ME"

More accounts don't change that.

[![HAC AUTOBAN - Kayla](http://img.youtube.com/vi/qqk87BiBuFs/0.jpg)](http://www.youtube.com/watch?v=qqk87BiBuFs)
