### ISSUE TITLE
Why am I on this list?

### ISSUE THREAD

**Issue by MCiLuZiioNz** [MFSiNC/SkidCheck-2.0#33]
My SteamID STEAM_0:0:26625390 is on this list for being a part of a group called "mybodyishaking" but I have no idea what that is?

**Comment by MFSiNC** [comment]
You're in a bad steam group. Add "http://steamcommunity.com/groups/" to the group name.

**Comment by MCiLuZiioNz** [comment]
Oh, sorry I was invited to the group by a friend. I have left it.

**Comment by MFSiNC** [comment]
I'll remove your ID in the morning.
