### ISSUE TITLE
I'd like my ID removed.

### ISSUE THREAD

**Issue by Fiiily** [MFSiNC/SkidCheck-2.0#35]
Can't really provide proof that I don't cheat since it's impossible to do so. I own my own server and I joined with the express intent of testing HeX's anticheat since I've heard of it.

**Comment by Fiiily** [comment]
oh, I should PROBABLY mention who I am. Aireesan/therealaireesan/"Troll names?"

**Comment by MFSiNC** [comment]
```
HAC U160223 @ [28.02.16 11:32:18PM] for Aireesan (STEAM_0:0:69527423)

AutoBANNED:
[00:21] AimbotC++
[00:21] lua/Herav4.lua
[00:21] lua/menu_plugins/modules/roc.lua
[00:22] SkidCheck_AlreadyGot: "Member of hack/troll group: anti-cheatsquad",

AutoBANNED @ [28.02.16 11:34:25PM @ 02:27] -- END LOG
```

![](http://i.imgur.com/kgZgngX.jpg "'Testing' HAC? Indeed.")

**Comment by Fiiily** [comment]
Hera was there to see if it would detect LUA cheats, C++ cheats were there
to see if it would detect C++ cheats.
My plan was to get added to SkidCheck to see if it detected it fully, and
then appeal.
