### ISSUE TITLE
I'd like my ID removed from the list

### ISSUE THREAD

**Issue by Goo132** [MFSiNC/SkidCheck-2.0#36]
Hello,my proof that im not a cheater, that i didnt even use the cheat that you have detected.
i got the cheat(bitchbot) from someone that entered my friend's sandbox server, and started to talk to us and he said that he can protect the server from cheater.....
later, i talked to him on skype and he asked me to try his new cheat(bitchbot). at the start, i refused but later on i accepted the offer, but after i tried the cheat once i deleted it because i felt bad that i used a cheat. i used the cheat JUST in singelplayer and in my friend server(he let me) JUST for trying the cheat.
after that, i searched on the internet for an anti-cheat because i was going to open a server, and i found the HeX anti-cheat. i wanted to see how it works in his server and some how it detect the cheat that i didnt turned it on at all!! please remove me from the list, every time i enter a server that skid check is installed, the admins bans me :( please :(

**Comment by Goo132** [comment]
my steam ID is STEAM_0:0:61734191

**Comment by MFSiNC** [comment]
Having cheats installed will still get you banned. You had 5 cheat DLLs and 2 lua cheats + a bad keybind.

```
HAC U150628 @ [12.07.15 12:19:41PM] for MrRoy (STEAM_0:0:61734191)

MrRoy
STEAM_0:0:61734191
http://steamid.co.uk/profile/76561198083734110

lua/bitchbot.lua
lua/sashahek.lua

lua/bin/gmcl_cat_win32.dll
lua/bin/gmcl_cvar3_win32.dll
lua/bin/gmcl_dickwrap_win32.dll
lua/bin/gmcl_nyx_win32.dll
lua/bin/gmcl_spreadthebutter_win32.dll

Bind="n" "bitchbot"

# SOUND: Horrible person
# SOUND: 6 SECONDS TO GO
```

**Comment by Goo132** [comment]
So will you remove me from the list?

**Comment by Goo132** [comment]
?????

**Comment by Goo132** [comment]
i deleted this cheat before a long time...
