### ISSUE TITLE
Why the fuck am I on this?

### ISSUE THREAD

**Issue by 404UserNotFound** [MFSiNC/SkidCheck-2.0#37]
https://github.com/MFSiNC/SkidCheck-2.0/blob/master/lua/SkidCheck/sv_SkidList_I.lua

`["STEAM_0:1:28177988"] = "Member of hack/troll group: urafagetur",`

Take me off this fucking bullshit malicious addon's ban list. I don't feel like being banned from a bunch of servers (that are stupid enough to use this piece of shit addon) just because you have a vendetta against a group that I only joined for the express purpose of inviting asshats like yourself to when they piss me off.

**Comment by MFSiNC** [comment]
You were on the list because you were a member of that bad group.
Your ID is removed and will sync in a few hours.

**Comment by 404UserNotFound** [comment]
> You were on the list because you were a member of that bad group.

It's not up to you to decide what groups are bad and what ones fucking aren't.

It's idiots like you and HeX _(HeX's bullshit 'anticheat' likes to search through people's personal files and look for instances of the word "hack", and then delete people's personal config files without their permission)_ that are really fucking up the Gmod community.

I know you probably get this a lot, but I think you should kill yourself.


> Your ID is removed and will sync in a few hours.

Well it's good that it's been removed, but I really don't give a fuck if it's synced or not because I don't go on any servers that run this bullshit addon.
