### ISSUE TITLE
Remove me please. 

### ISSUE THREAD

**Issue by HeyBanditoz** [MFSiNC/SkidCheck-2.0#38]
I never used scripts on your server, so why am I on the list? If like to be removed. 

["STEAM_0:1:58121051"] = "Pioneer Road/heybanditoz, Falcos scripts",

**Comment by MFSiNC** [comment]
You're on the list because you have them.

**Comment by HeyBanditoz** [comment]
So you're banning people from your server who haven't even joined yet, and you're judging people based on their subscribed addons?

**Comment by MFSiNC** [comment]
Correct.
I don't want people who have falco's scripts joining the UHDM server.

**Comment by HeyBanditoz** [comment]
May I ask what you have against Falco's scripts? I only had them for use in DarkRP (or places that allow client-side Lua, which is completely fine). I wasn't planning on using it anywhere else. You're trying to keep cheaters off your server with your addon, which I respect, but a lot of people are falsely on that list.
