### ISSUE TITLE
false listing in list M:  	["STEAM_0:1:16716622"] = "Member of hack/troll group: MPGH",

### ISSUE THREAD

**Issue by Shigbeard** [MFSiNC/SkidCheck-2.0#39]
["STEAM_0:1:16716622"] = "Member of hack/troll group: MPGH",

Not true

**Comment by MFSiNC** [comment]
Updated. Will sync in a few hours.

**Comment by Shigbeard** [comment]
Still false, http://steamcommunity.com/groups/TooMuchHax is not a hacker/troll group

**Comment by Shigbeard** [comment]
also I don't think i've had nearly that many troll names.

**Comment by Shigbeard** [comment]
lastly the vac ban was from COD, literally days before they shut down vac

**Comment by MFSiNC** [comment]
https://steamid.eu/profile/76561197993698973
