### ISSUE TITLE
Please add another troll group

### ISSUE THREAD

**Issue by Noiwex** [MFSiNC/SkidCheck-2.0#40]
http://steamcommunity.com/groups/NxServ

they go around and crash servers over and over, i think they should be culled

**Comment by MFSiNC** [comment]
Not a cheating/troll group. Only 9 of their members are already on the database, out of over 15,000.

**Comment by ExtReMLapin** [comment]
stop being a nigger

**Comment by Noiwex** [comment]
Racist

**Comment by ExtReMLapin** [comment]
im not racist my dog is black
