### ISSUE TITLE
SkidCheck fails to update properly when using server.cfg for auto-updates on server start

### ISSUE THREAD

**Issue by RyanJGray** [MFSiNC/SkidCheck-2.0#42]
When starting SkidCheck's updates automatically through the server.cfg file ![ss 2016-05-22 at 07 08 53](https://cloud.githubusercontent.com/assets/3857322/15455585/b23a7f72-2050-11e6-9620-1534c41feddf.png)

it appears to glitch and say that the local lists differ by 3,246 IDs.
![ss 2016-05-22 at 07 04 24](https://cloud.githubusercontent.com/assets/3857322/15455574/2ffd3ba8-2050-11e6-80d8-dec256a8e404.png)

However, if you start an update manually (sk_update) it say's the lists are up-to-date (And will work normally)

**Comment by MFSiNC** [comment]
Hmm, try not running ```sk_update``` in server.cfg, it does this on map start anyway.

Re-download a fresh copy of the addon and replace it, the lists may have got out of sync.
See if that works.

**Comment by RyanJGray** [comment]
Okay will try that.

**Comment by RyanJGray** [comment]
Strange, re-downloaded a fresh copy of SkidCheck and it only seems to start the list update when a player connects?

**Comment by MFSiNC** [comment]
Ah it uses a timer to do it. Timers don't start running until the first player joins. No worry.

**Comment by RyanJGray** [comment]
Ah okay, thought it was a bug. So I guess the issue is resolved (You might want to put in the readme to not use sk_update in the server.cfg file)

**Comment by MFSiNC** [comment]
Will do, I'll edit the readme when I'm back on my main PC in a few days.

**Comment by RyanJGray** [comment]
Also off-topic but, is the server going to be locked for much longer?
