### ISSUE TITLE
SkidCheck claims that lists are out-of-date when they are actually up-to-date

### ISSUE THREAD

**Issue by RyanJGray** [MFSiNC/SkidCheck-2.0#43]
If a bot joins it will start the auto-update but will claim that the lists are out-of-date when they are in-fact up-to-date (Or sort of up-to-date), I think this has something to do with my last issue involving the server.cfg file.

![ss 2016-05-30 at 09 38 16](https://cloud.githubusercontent.com/assets/3857322/15658024/61270a50-26af-11e6-89a5-a402e4c774c0.png)

**Comment by RyanJGray** [comment]
#42

**Comment by MFSiNC** [comment]
Was this a fresh download of SkidCheck from GitHub? your screenshot says it updated to 150,682, from 149,375 in local lists, meaning the local lists were slightly older, and the update worked as it should.

Re-download a totally fresh copy of SkidCheck and check again, I just tried it and it worked for me:
Older copy:
![](http://i.imgur.com/cuPfQEG.png)

Fresh download:
![](http://i.imgur.com/w6GpwJB.png)

**Comment by RyanJGray** [comment]
Yes it was a fresh download, I thought that something was wrong because I've been testing things locally (Around every day) and that's updated loads of times (So I presumed it was incorrect but it seems to have just been a mistake on my side)
