### ISSUE TITLE
banned?????

### ISSUE THREAD

**Issue by bubbie** [MFSiNC/SkidCheck-2.0#45]
hello i was put on this skiddy thing and i dont know why can you please tell?
cause i cant go on any server any more i go on server and it say im a cheater but im not :(
its getting really really sad because i cant play anywhere because all servers have skidcheck...

**Comment by MFSiNC** [comment]
What's your SteamID?
I highly doubt all servers have SkidCheck, since Falco disables it in DarkRP, and it seems everyone hates it.

**Comment by bubbie** [comment]
thank you kind sir my steamid is 76561198108596120

**Comment by MFSiNC** [comment]
[SK.."0:74165196"] = "Bubbie/bubbieb/Bubbles/Troll names, sv_allowcslua bypass (Kone), 3 terrible cheat scripts, Member of 15 hack/troll groups, Spamming HeX's profile",

**Comment by bubbie** [comment]
but i dont understand??? what did I do i dont get it :(

**Comment by MFSiNC** [comment]
```
HAC U160424 @ [17.05.16 09:37:59AM] for Bubbie (STEAM_0:0:74165196)

Bubbie
STEAM_0:0:74165196
http://steamcommunity.com/profiles/76561198108596120

SkidCheck: Member of hack/troll group: 911insidejob

CVCheck_Err: sv_allowcslua == CVAR_NOT_FOUND
CVCheck_Bulk: kone_lua  [[1]] Res(0)

# SOUND: Horrible person
# SOUND: SK_BombFail
DoWhat started
DoWhat received
# SOUND: Run around for so long
# SOUND: 6 SECONDS TO GO
```

**Comment by bubbie** [comment]
i dont see anything here that suggest i did anything bad? i dont even kno what united host is i only play on hl2rp dude

**Comment by MFSiNC** [comment]
You joined my server and had kone_bypass loaded. You (and 15 other people) spammed my Steam profile about an hour ago.
