### ISSUE TITLE
Please unban me.

### ISSUE THREAD

**Issue by towergame** [MFSiNC/SkidCheck-2.0#46]
Hello. Why was I added to the skidcheck list? :(((((((( I want to play mod of the G but it won't let me on anyservers because all servers have skidcheck. Please remove me ;((((((.

**Comment by bubbie** [comment]
yeah ikr i was put on there for no reason too

**Comment by MFSiNC** [comment]
What's your SteamID?
I highly doubt all servers have SkidCheck, since Falco disables it in DarkRP, and it seems everyone hates it.

The reasons are I don't want you joining the UH server.

**Comment by MFSiNC** [comment]
Nevermind,
```[SK.."1:72182440"] = "Captain Russia/towergame, Spamming HeX's profile, "..GG.." 911insidejob",```
