### ISSUE TITLE
	[SK.."1:68209808"] = GG.." TooMuchHax", false listing

### ISSUE THREAD

**Issue by Shigbeard** [MFSiNC/SkidCheck-2.0#47]
why am I listed here

**Comment by MFSiNC** [comment]
You have 3x VAC bans, your custom URL is ``aimwaretester77698``, and you're a member of that cheating group.
You're not welcome on the server.

**Comment by Shigbeard** [comment]
like i said. Nothing wrong.

Also obligatory note that you have psychological issues. Please see a health care professional.
