### ISSUE TITLE
0 IDs in local lists!

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#51]
Hi,

tried you addon but no ids are read from all lists (downloaded and placed everything).

[SkidCheck] Ready. 0 IDs in local lists!

No other Lua errors found.

**Comment by MFSiNC** [comment]
Hi, hmm, I just tried a freshly downloaded zip from GitHub on a local SRCDS instance, seems to work fine
![](http://i.imgur.com/bH211TO.png)

I'll add a list size check error message.

**Comment by MinIsMin** [comment]
[SkidCheckSync] Downloading list 17/18
[SkidCheckSync] Downloading list 18/18
[SkidCheckSync] ERROR: LIST FORMAT VERSION CHANGE, Can't sync lists! (doesn't happen often)
[SkidCheckSync] ERROR: (vGit: 2.1 != vLoc: nil)
[SkidCheckSync] ERROR: Please re-download this addon from https://github.com/MFSiNC/SkidCheck-2.0

(System: Ubuntu Server LTS 16.04)

**Comment by MFSiNC** [comment]
It seems its having trouble loading the local lists on non-Windows machines, I'm looking into it now

**Comment by MFSiNC** [comment]
Just pushed an update, re-download the addon and try now. It may have been a file case problem.

**Comment by MinIsMin** [comment]
[SkidCheck] Error loading local lists, this should never happen! (Got 0!)

[SkidCheck] Please re-download this addon from https://github.com/MFSiNC/SkidCheck-2.0

**Comment by MFSiNC** [comment]
I'll prepare a test system with Ubuntu Server LTS 16.04 and test it there. Will let you know

**Comment by MinIsMin** [comment]
Also, no files created in /data

**Comment by MFSiNC** [comment]
/data files are only written if players are encountered. As it didn't load, that's to be expected.
I'm setting up the Ubuntu system now to test it, I suspect its still related to filename casing.

**Comment by MFSiNC** [comment]
Fixed. Fully working on Ubuntu 16.04, it seems Lua won't load CaseSensitive folders, but it will files.
Download the latest copy and try now.

![](http://i.imgur.com/bfInnST.png)

**Comment by MinIsMin** [comment]
I don't know what's wrong...

[SkidCheck] Error loading local lists, this should never happen! (Got 0!)

[SkidCheck] Please re-download this addon from https://github.com/MFSiNC/SkidCheck-2.0

**Comment by MFSiNC** [comment]
Did you rename the addon folder, it has to **all be lowercase** for it to work. All folders under addons/ have to be lowercase, including subfolders.

If it still doesn't work I don't know why, I set up a fresh Ubuntu VM and tested it, fixed the case issue, and it works on this end.

![](http://lh6.ggpht.com/-z_BeRqTrtJE/T2sLYAo-WmI/AAAAAAAAAck/0Co6XilSmNU/WorksOnMyMachine_thumb%25255B4%25255D.png)

**Comment by MinIsMin** [comment]
Your '/addons/myskid/lua/SkidCheck' was the error. (Got it from github)

[SkidCheck] Ready, SK003. 173,177 IDs in local lists! (Will sync on 1st join)

[SkidCheckSync] Fetching index..
[SkidCheckSync] ERROR: GetIndex JSON decode error (Got table)

**Comment by MFSiNC** [comment]
Yes, I pushed an update that renamed all the folders to lowercase a few mins ago.

**Comment by MinIsMin** [comment]
Thanks. My system has only overwritten the folder without changing the uppercase to lowercase.
It's working.

**Comment by MinIsMin** [comment]
Is it right that the new ID's are not saved in a file?
Becuase on every map change, the new ID's are downloaded and no files are changed.

[SkidCheckSync] Download complete, lists up to date. 121 new IDs :)

[SkidCheck] Ready, SK003. 173,298 IDs in local lists! Sync complete :)
