### ISSUE TITLE
Another Workshop Script

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#52]
Script: http://steamcommunity.com/sharedfiles/filedetails/?id=721101577
SteamID: STEAM_0:0:92252739
Reason: Writing & releasing Cheats

Other question:

Why is Lenny (ID: ':30422103') listed twice? (List A and Q) Isn't one line enough for him?

**Comment by MFSiNC** [comment]
Added him. Will sync soon.

Lenny's ID being in there twice was a bug, I thought I de-duplicated the lists before, guess I missed one.

**Comment by MinIsMin** [comment]
1:50714411 is also twice in lists (A and Q)

**Comment by MFSiNC** [comment]
Yes, I'm writing a de-duplicating function now, will remove all dupes soon.
It won't bother the script having them there, one just overwrites the other. Will be fixed soon.

**Comment by MFSiNC** [comment]
De-duplicated.

![](http://puu.sh/qf82A.png)
