### ISSUE TITLE
They keep popping up...

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#53]
Just to let you know: http://steamcommunity.com/sharedfiles/filedetails/?id=732215911
SteamID already blacklisted: 1:88828403
You can add the following reason: writing & releasing hacks

Another person (found in Script Comment):
SteamID: 0:51913704 (Name: 'Gas the Kikes Race war now')
Certified Reason: achievement hack (has no workshop uploads but 'Mega Upload')
Probably Reason: Using of Bee's Scripts, 1x VAC

**Comment by MFSiNC** [comment]
```
	["0:51913704"] = "Troll names, VAC banned, "..GG.." honorableposters",
```

I've updated the reasons and blacklisted the addon.
