### ISSUE TITLE
Gscripts, HL Scripts

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#55]
New Workshop Hack Scripts:

https://steamcommunity.com/sharedfiles/filedetails/?id=713893251
SteamID Creator 1: 1:94475988
SteamID Creator 2: 0:47188115
SteamID Creator 3: 1:95831521

https://steamcommunity.com/sharedfiles/filedetails/?id=701694374
SteamID Creator 1 (already listed): 1:4154719
SteamID Creator 2 (already listed): 1:171775494

**Comment by MFSiNC** [comment]
All added, will sync soon.
