### ISSUE TITLE
Got some juicy skid info for you

### ISSUE THREAD

**Issue by Shigbeard** [MFSiNC/SkidCheck-2.0#56]
http://steamcommunity.com/id/fakeangles/ or http://steamcommunity.com/profiles/76561197968575167/

Doxing, Skidding, god complex, c+p code. Enjoy stroking your ego hex. I may dislike you and you dislike me but I know you LOVE adding to your list of skids. 

![https://i.sli.mg/gUSI7Q.png](https://i.sli.mg/gUSI7Q.png)
![https://i.sli.mg/K9swPh.png](https://i.sli.mg/K9swPh.png)

**Comment by BeeTeeGee** [comment]
I can vouch for Shig, the person in question (Dark) initially got infurated at me solely because of a FP thread that I was associated with, and Shig put his two cents in and everything went wild, to say the least

**Comment by MFSiNC** [comment]
He's already in the list:
```	["1:4154719"] = "Warden1142/deltasword100/DarkCide/dmrradio/Serverwatch, Server takeovers,C++ hacks,speedhacks,releasing hacks, propkiller,Member of many hack/troll groups, BAN ME FOREVER",```

I'll update his reason.

**Comment by Shigbeard** [comment]
What?!? He is serverwatch?!?

Are you SURE?!?

**Comment by MFSiNC** [comment]
Acording to the database, yes. Check previous versions of List_A, he's been there years.

Google ```STEAM_0:1:4154719```

**Comment by Shigbeard** [comment]
Holy shit I'm actually dying. Your outstanding record-keeping just made my day HeX.

**Comment by BeeTeeGee** [comment]
He's made his profile private in response, the fact that he's actually serverwatch just made my whole day lol
