### ISSUE TITLE
Adding more people to the list

### ISSUE THREAD

**Issue by BeeTeeGee** [MFSiNC/SkidCheck-2.0#57]
* all SteamIDs besides yours are from my own personal list

* also, did you get the top SteamIDs that are on list A from my own?

`["0:84408790"] = "sp00k/rdude/The Terminator/Troll names, 4x VAC bans, "..Snix..","..GG.." Letsraidgmodservers,myg0t_international,vacbannedlol"` 

^ Has an alt:  `["STEAM_0:1:119939764"] = true, -- sp00k/rdude alt`

Not forgetting the fact that he was VAC'd only 8 days ago on his main (at the time of typing this out)

`["STEAM_0:1:98949755"] = true, -- aajake13
["STEAM_0:1:123867811"] = true, -- aajake13 alt 
["STEAM_0:0:141401625"] = true, -- aajake13 alt 
["STEAM_0:0:141369684"] = true, -- aajake13 alt `

^ Big ole 'skid', you can check here for proof (top videos): https://www.youtube.com/channel/UCtTimqYs3sbOuUoA2ua-CeA

`["STEAM_0:0:75511012"] = true, -- Butters/Carrot Eater
["STEAM_0:0:155846943"] = true, -- Butters/Carrot Eater alt`

^ Also in affiliation with aajake13

**Comment by MFSiNC** [comment]
All added.
```
1:119939764

1:98949755
1:123867811
0:141401625
0:141369684

0:75511012
0:155846943
```

And yes, I parsed your list through, and all but **5** of them were already on SkidCheck. I updated their reasons.

**Comment by BeeTeeGee** [comment]
I was wondering, because there was no way you could've been able to get:

`["STEAM_0:1:45586871"] = true, -- Sackson`

Was that a result of the FP thread?

**Comment by MFSiNC** [comment]
Yes it was the FP thread, although that ID was already in the list before, as:
```	["1:45586871"] = GG.." KuKluxKarnival",```

**Comment by BeeTeeGee** [comment]
You can have my whole list if you really want to, it gets updated regularly (people I don't want using my addon for a good reason)

I don't know if I also have to make a separate issue for my listing but, I've never went by the name "btgboy7" and I've never DDoSed your server (which I also asked about on your Steam profile comments but gave me my listing which was not what I requested)

**Comment by MFSiNC** [comment]
The alias "btgboy7" was from https://steamid.eu/profile/76561198137922535
I'll update the reason.

The server was DDoSed a few hours after you got banned. It was the likely blame.

Also just wondering why I'm number 1 on your "Nope" list? You know I don't use cheats and only play GMod on UnitedHosts. I don't care about being on it, just interested as to why.

**Comment by BeeTeeGee** [comment]
At that time when I attempted to join the server, I was already banned so there would be no point in doing so

Regarding the last question: `people I don't want using my addon for a good reason among other things.`

Never said you used cheats, also you're number one because of the positioning of my table, I add more from the top

**Comment by BeeTeeGee** [comment]
And now you added "Ban Evasion" and still kept "DDoS" in, first: those alternate accounts aren't even for the sole purpose of joining your server, and second: you still don't have sufficient proof that I hit you. Keyword: "blame". Not fact.

**Comment by MFSiNC** [comment]
Reason updated.

Connection logs show 3 of your accounts trying to join.
```
[16.08.15 04:58:25AM] - (BLOCKED) Bee T. Gee [#29609483] (STEAM_0:1:88828403)
[24.08.15 11:12:41PM] - (BLOCKED) bee_tee_gee [#38404042] (STEAM_0:1:115212069)
[21.11.15 09:27:50AM] - (BLOCKED) the big bee man [#40508035] (STEAM_0:1:121524040)
```

**Comment by BeeTeeGee** [comment]
Those aren't recent? You had already put my alts there before anyways, no point in joining.

**Comment by MFSiNC** [comment]
The alts were already in the list for quite some time. I linked them together with the same reason as the main recently.

**Comment by BeeTeeGee** [comment]
I know they were in the list for quite some time, that's why I previously stated that. What I meant by "Those" in "Those aren't recent" is the dates.
