### ISSUE TITLE
More Hack Scripts

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#58]
Hack: http://steamcommunity.com/sharedfiles/filedetails/?id=736320176
BHOP: http://steamcommunity.com/sharedfiles/filedetails/?id=736576534

SteamID: 1:79501012
Reason: Writing & Releasing Hack, BHop Scripts

Assigned group:
http://steamcommunity.com/groups/addon_fabric
SteamID 1: 1:79501012 (as stated above)
SteamID 2: 1:43886943
SteamID 3: 0:93230518
SteamID 4: 1:68752861 (already in your lists)
SteamID 5: 1:60000040
SteamID 6: 1:77250593

**Comment by MFSiNC** [comment]
Added:
```	["1:79501012"] = "mashaBiceps/Patrick/xtarion_mashabiceps, Writing hacks (EasyScript)",```

Not adding the group yet, as it isn't all cheats.

Also if you could format any additions in this way, it makes it easier to add:
```["1:13371337"] = "Name/AlsoKnownAs/CustomURLIfAny, VAC Status, ReasonsForBeingBanned",```
See List_A for how they're formatted.
