### ISSUE TITLE
It's high season

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#59]
Workshop - Hack: http://steamcommunity.com/sharedfiles/filedetails/?id=737821519
Group: http://steamcommunity.com/groups/GmodCheat

Some of them are already in your list (most in List A), I updated the reasons:

`["0:766427"] = "LonelyWolf/Lua_, Writing&releasing Hacks, GmodCheats",`
(already in List K for 'suicideisthebestoption')
`["0:149000553"] = "Alpha/TheSpooner, GmodCheats",`
`["0:69870071"] = "CoryInTheHouse/Wally The Walrus/BallLint, GmodCheats",`
`["1:81881925"] = "DJ Dark/K.Y.S., GmodCheats",`
`["1:58670587"] = "Edge/Brian, VAC banned, GmodCheats, gaynig",`
`["0:61922768"] = "Nanovirus/Verified, GmodCheats",`
`["1:115653024"] = "NBK/Noah, GmodCheats",`
`["1:174245744"] = "Method/.Xnightf0x, GmodCheats, PropKillNA",`
`["1:66953556"] = "The Nine Dogs/The Nin/hashtag_swiggyswag, VAC banned, GmodCheats, putanendtoracism",`
`["1:86794424"] = "big boss/Snake/Troll names, GmodCheats",`
`["1:80091825"] = "heloplayer/d0shtheking/Troll names, Server takeovers, VAC banned, "..GG.." antibirusnet,urmamaisdonebyme,complimentmyvacban,GmodCheats Ban evasion (Alt 1:103330387),`
`["0:82087808"] = "BUGGS BUNNY/Troll names, GmodCheats",`
`["1:84420145"] = "Detail/PersonalVPN/Troll names, GmodCheats",`
`["0:56478202"] = "EagleEye117, GmodCheats",`
`["0:72457577"] = "g-modder/Frobro3.0/Phys Frobro, snixzz cheat user, 2x VAC bans, "..GG.." darkscriptsv1,GaingRape, GmodCheats",`
`["0:92416108"] = "Krippen/ecig/Troll names, Multiple VAC Bans, valuev, GmodCheats",`
`["1:64777074"] = "MrWeegeeMan, Dismay (STEALING FILES), 2S: sv_allowcslua, ban me, "..GG.." darknevercomeback, GmodCheats"`
`["0:54838196"] = "PalestinianMaan/BobbyG/105thGamer, GmodCheats, noobsmashers",`
`["0:180038467"] = "PolitikZ/Speak Up Kieran Lad/Jewkill3r, GmodCheats",`
`["1:167236215"] = "Shims/coolman420/dotheshimmie/Trollnames, GmodCheats",`
`["1:112541237"] = "BassBat/TacosCANrap/Tacos, snixzz cheat user, "..Snix..","..GG.." annoyingprogamers, GmodCheats",`
`["1:33685014"] = "Whale Tits/Troll names, DDoS, Server takeovers, VAC banned, "..GG.." poki,AIMWARE, GmodCheats, BAN ME FOREVER",`

This group (members) may be of interest:
http://steamcommunity.com/groups/cakeisdead

**Comment by MFSiNC** [comment]
```["0:766427"]``` didn't write LESP, but I've updated his reason.
Also the whole group is already banned.

Note, if you're pasting me a list of IDs to update that are already in there, keep their existing reasons and add the new one to the end. Just listing "GmodCheats" and not "Member of hack/troll group:" before doesn't make sense.

Updating and adding those IDs now.
