### ISSUE TITLE
DarkRP

### ISSUE THREAD

**Issue by MainFighter** [MFSiNC/SkidCheck-2.0#6]
Just so you know Falco just did this...
https://github.com/FPtje/DarkRP/commit/a7de68b05f06640a6686eea29a78509dfecc7abb

**Comment by MFSiNC** [comment]
Probably because he's a propkiller and hundreds of users of his "Falco's scripts" are in the database.

**Comment by MainFighter** [comment]
Yeah, I know...
Just thought I would tell you.

Looks like I'm gonna have to remove that piece of code from DarkRP every time it gets updated or bypass it, I'll figure it out when I get home.

**Comment by MFSiNC** [comment]
I'll fix it tomorrow, he shouldn't disable other addons (that aren't affecting his gamemode) just because he doesn't like them.
Server owners manually install SkidCheck, its their choice to run it on their server, not his.

**Comment by MainFighter** [comment]
That's exactly what I agree with really...

And also I was just wondering but one of my mates ended up getting on the list because his stupid.
https://github.com/MFSiNC/SkidCheck-2.0/commit/24130e23b10578ea4afbdd822f552586c2428dc0
That guy, just wondering if I could get him removed or something.

Doesn't really matter if he doesn't just thought I would ask :)

**Comment by HDG-MrDeeJay** [comment]
@MFSiNC He disabled it because its malicious to list tens of thousands of players with little to no evidence what so ever.

Include evidence of hacks IN THE MESSAGE, or take people off it if you want an ounce of credibility

**Comment by MFSiNC** [comment]
@HDG-MrDeeJay:
The messages do contain their reasons, newer ones (at the top of list A) contain a lot more info than the ones added 4-5 years ago.

SkidCheck is the list of people who I don't want playing on my server. It was originally the HAC database, and was released here for anyone to use for any reason. Not to cause drama.

If you don't like it, don't use it. I'm not going to bypass falco's disabling of the SkidCheck.

**Comment by MainFighter** [comment]
@MFSiNC 
I agree with all of that really. Its up to the server owners/managers if they want to use it or not.

Anyway, I just wanted to tell you not cause drama.
I did that so its all good.

**Comment by AlauraLeafLoveless** [comment]
Mind if i contribute, the fact that your talking about saying shouldn't disable addons that are specifically running off of "his" own code, he owns the code, he can do whatever the fuck he wants with it, just putting this out there.
