### ISSUE TITLE
STEAM_0:1:5762375 Listed? 

### ISSUE THREAD

**Issue by Link2006** [MFSiNC/SkidCheck-2.0#60]
Hello, 

I am in the list sv_SkidList_A.lua and i'd like my SteamID removed, can we talk this out and figure out why i was added in the first place? 

What kind of proof do you want as well, i'm willing to provide whatever you require.

**Comment by MFSiNC** [comment]
Hi, your ID has been removed.
I think it was there from a time 5 years ago when you joined the server and set something off. I'll see if I still have the logs.

**Comment by MFSiNC** [comment]
Found it, it was FapHack config files in 2011.
```
[HAC85_U125] [27-07-11 12:02:29AM] - Logged: -=NrK=- Link2006 *Qc <link2006> (STEAM_0:1:5762375) - Datafile=data/faphack_entities.txt-29 (*faphack*.txt) [[_Out_{	_1_		_player_]]
[HAC85_U125] [27-07-11 12:02:29AM] - Logged: -=NrK=- Link2006 *Qc <link2006> (STEAM_0:1:5762375) - Datafile=data/faphack_friends.txt-13 (*faphack*.txt) [[_Out_{}]]
[HAC85_U125] [27-07-11 12:02:30AM] - Logged: -=NrK=- Link2006 *Qc <link2006> (STEAM_0:1:5762375) - Datafile=data/faphack_entities.txt-29 (*hack*.txt) [[_Out_{	_1_		_player_]]
[HAC85_U125] [27-07-11 12:02:30AM] - Logged: -=NrK=- Link2006 *Qc <link2006> (STEAM_0:1:5762375) - Datafile=data/faphack_friends.txt-13 (*hack*.txt) [[_Out_{}]]
```

**Comment by Link2006** [comment]
Thanks for the fast response and removal, I wonder if it was actually a server using that, which caused the settings to be saved automatically, because i somewhat remember these being on servers to "administrate" things but i might be confused with something else. Oh well i still learned to not join random servers since then :P
