### ISSUE TITLE
New Hack Script

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#61]
Workshop Script: http://steamcommunity.com/sharedfiles/filedetails/?id=744411946
Cheat Group: https://steamcommunity.com/groups/CyanideCheats

Uploader: `["0:107992661"] = "Moosicorn/Owlicorn/officialmoosicorn/iamcyaegha/Function alt?, Writing & releasing hacks, VAC banned, snixzz cheat user, "GG.." CyanideCheats, "..Snix..", MPGH",` (already in List A)

Moderator: `["0:54784469"] = "Pxlated/Richard Dawkins/Nightmarish Pxl, "GG.." CyanideCheats",`
Moderator: `["1:41808665"] = "ButterDick/TheHolocaustwasFaked/Troll names, VAC ban, "GG.." swag_hack, CyanideCheats",` (already in List L)
Cheat User: `["1:126227488"] = "Sir_tipsy, "GG.." CyanideCheats",`

**Comment by MFSiNC** [comment]
Checked and updated all IDs. Thanks.
