### ISSUE TITLE
New Workshop Script

### ISSUE THREAD

**Issue by MinIsMin** [MFSiNC/SkidCheck-2.0#63]
Workshop Item: http://steamcommunity.com/sharedfiles/filedetails/?id=758227218
Uploader: http://steamcommunity.com/id/maincrave (SteamID: 1:96502950)
Already listed in A:
`["1:96502950"] = "crave, snixzz cheat user",`
Should be changed to: 
`["1:96502950"] = "crave, Cyanide Cheats, snixzz cheat user, Writing & releasing hacks (Pasteware)",`

Verified Cheat user (http://steamcommunity.com/workshop/filedetails/discussion/758227218/350540974008105017/): 
`["1:71564718"] = "snixzz cheat user @ 06-08-2016, "..GG.." ididnothither",` (List A)
Should be:
`["1:71564718"] = "Judge, PasteWare, snixzz cheat user @ 06-08-2016, "..GG.." ididnothither",`

**Comment by MFSiNC** [comment]
Updated, will sync soon.
