### ISSUE TITLE
List A contains an old SteamID of mine

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [MFSiNC/SkidCheck-2.0#7]
["STEAM_0:1:68209808"] = "DeeJay, VAC ban, autobanned for hacks, google his steamid",

Lets start by explaining the (two) VAC bans. First 1: TF2. VAC banned due to a texture pack which got blacklisted by VAC because it removed some textures associated with players (Removed annoyingly large hats so I could snipe)

2: MW2: Banned because I hosted a modded lobby, only so I could host a lobby instead of being automatically sent to a "Scoutsknivesnades" modded server

Now lets get into hacking in Garry's Mod.

There has been only 1 time I have hacked outside of my own servers, and that was at the request of staff of that server.

So to ban me based solely on tidbits you find online without ANY solid evidence is VERY irresponsible. I've been a hard working LUA developer, admin, and Web Developer, respected by my peers, and have only ever hacked in pentesting. (For the children in the room, that means "Penetration testing" where you attempt to break through your own defenses just to see where they need improving)

Please remove my SteamID now.

**Comment by MFSiNC** [comment]
Removed. Will sync tomorrow afternoon.

**Comment by HDG-MrDeeJay** [comment]
Thank you for understanding. I appreciate your timely response.
